# Site settings
title: Xinyu Li's Webpage
email: joey.xinyuli@tamu.edu
description: Academic webpage of Dr. Xinyu Li
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Xinyu Li (Joey) <br/>
  Postdoctoral Researcher<br/>
  Texas A&M Univeristy

location: >
  Texas A&M Univeristy<br/>
  788 Ross St<br/>
  College Station, TX 77840

contact: >
  <a href="mailto:joey.xinyuli@tamu.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Xinyu via email</a> <br/>
  <a href="https://github.com/joeyleehk"><i class="fa fa-github fa-1x"></i> GitHub</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
#  - name: research
  - name: software
  - name: teaching
  # - name: blogs
  # - name: talks
  # - name: team

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
